services:
  postgres:
    image: postgres:16-alpine
    container_name: edureyting_postgres
    environment:
      POSTGRES_DB: edureyting
      POSTGRES_USER: edureyting_user
      POSTGRES_PASSWORD: edureyting_secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edureyting_user -d edureyting"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: edureyting_redis
    command: redis-server --appendonly yes --requirepass "redis_secret"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_secret", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: edureyting_meilisearch
    environment:
      MEILI_MASTER_KEY: meilisearch_master_key
      MEILI_ENV: development
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:
